USE [TradesoftProblem151]
CREATE TABLE [dbo].[Analogs](
	[OriginalGoodslD] [int] NOT NULL,
	[AnalogGoodsID] [int] NOT NULL,
	[Reliance] [bit] NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_Analogs] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]